import type { Metadata } from "next";
import { Merienda, Open_Sans, Caveat } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import "animate.css/animate.min.css";
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Script from 'next/script';

// Font configuration
const merienda  = Merienda({
  subsets: ['latin'],
 variable: '--font-merienda',
});
const openSans = Open_Sans({ subsets: ['latin'], variable: '--font-open-sans' });
const caveat = Caveat({ subsets: ['latin'], variable: '--font-caveat' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // optional
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${merienda.variable} ${openSans.variable} ${caveat.variable}`}>
        <Header />
        {children}
        <Footer />
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        />
      </body>
    </html>
  );
}
